steps:
- name: 'gcr.io/triggermesh/operator-sdk'
  args: ['build', 'gcr.io/$PROJECT_ID/operator:$REVISION_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/operator:$REVISION_ID']
images: ['gcr.io/$PROJECT_ID/operator']
