{{- if not .Values.secrets.existingAuth0Secret }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-token
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  client_id: {{ required "Auth0 ClientID is required" .Values.secrets.auth0ClientId | b64enc | quote }}
  client_secret: {{ required "Auth0 ClientSecret is required" .Values.secrets.auth0ClientSecret | b64enc | quote }}
{{- end -}}
