apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: {{ include "triggermesh.fullname" . }}-kaniko
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  parameters:
  - description: The name of the image to push
    name: IMAGE
  - default: /workspace/Dockerfile
    description: Path to the Dockerfile to build.
    name: DOCKERFILE
  steps:
  - args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/key.json
    image: gcr.io/kaniko-project/executor:v0.7.0
    name: build-and-push
    volumeMounts:
    - mountPath: /secret
      name: kaniko-secret
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
