apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "triggermesh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  vhost.conf: |
    # Retain the default nginx handling of requests without a "Connection" header
    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }
    # Allow websocket connections
    proxy_set_header Upgrade    $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    server {
      listen 8080;
      location / {
        proxy_pass http://{{ include "triggermesh.fullname" . }}-fe-ui:8080;
      }
    }

  vhost-ui.conf: |
    server {
      listen 8080;
      gzip on;
      # Angular CLI already has gzipped the assets (ng build --prod --aot)
      gzip_static  on;
      location / {
        try_files $uri /index.html;
      }
    }
    # Redirect www to non-www
    # Taken from https://easyengine.io/tutorials/nginx/www-non-www-redirection/
    server {
      server_name "~^www\.(.*)$" ;
      return 301 $scheme://$1$request_uri ;
    }
