{{- if not .Values.secrets.existingGitHookSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triggermesh.fullname" . }}-githook
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.secrets.gitHookSecret }}
  secret: {{ .Values.secrets.gitHookSecret | b64enc | quote }}
{{- else }}
  secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end -}}
{{- end -}}
