apiVersion: v1
kind: Service
metadata:
  name: {{ include "triggermesh.fullname" . }}-k8s
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "triggermesh.fullname" . }}-k8s
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subsets:
- addresses:
  - ip: {{ .Values.k8sAPI.IP }}
  ports:
  - name: https
    port: {{ .Values.k8sAPI.port }}
