{{- if and (not .Values.image.existingPullSecret) .Values.image.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triggermesh.fullname" . }}-pullsecret
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "triggermesh.imagePullSecret" . }}
{{- end -}}
