{{- if .Values.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "triggermesh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - build.knative.dev
  - build.knative.dev
  - eventing.knative.dev
  - eventing.knative.dev
  - extensions
  - messaging.knative.dev
  - messaging.triggermesh.dev
  - rbac.authorization.k8s.io
  - serving.knative.dev
  - sources.eventing.knative.dev
  - sources.eventing.triggermesh.dev
  - tekton.dev
  resources:
  - apiserversources
  - awscodecommitsource
  - awscognitosource
  - awsdynamodbsource
  - awsiotsource
  - awskinesissource
  - awssqssource
  - awssqssources
  - azureeventhubsource
  - azurestorageblobsource
  - azurestoragequeuesource
  - brokers
  - builds
  - camelsources
  - channels
  - clusterchannelprovisioners
  - clusterchannelprovisioners
  - clusterrolebindings
  - clusterroles
  - configurations
  - containersources
  - cronjobsources
  - deployments
  - gcppubsubsources
  - githubsources
  - gitlabsources
  - inmemorychannels
  - kafkasources
  - kinesischannels
  - kuberneteseventsources
  - namespaces
  - pipelineresources
  - pipelineruns
  - pipelines
  - pods
  - pods/exec
  - pods/log
  - pods/logs
  - pubsubsources
  - revisions
  - rolebindings
  - roles
  - routes
  - secrets
  - serviceaccounts
  - services
  - sinkbindings
  - subscriptions
  - taskruns
  - tasks
  - triggers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "triggermesh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "triggermesh.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "triggermesh.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "triggermesh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ include "triggermesh.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
