apiVersion: app.triggermesh.io/v1alpha1
kind: TriggerMesh
metadata:
  name: example-triggermesh
spec:
  frontend:
    baseHost: cloud-test.tm.demo.vshn.net
    route:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
    authApiId: <REDACTED>
    auth0ClientId: <REDACTED>
    sentryDSN: https://<REDACTED>@sentry.io/
  backend:
    baseHost: app-test.tm.demo.vshn.net
    route:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
  secrets:
    auth0ClientId: <REDACTED>
    auth0ClientSecret: <REDACTED>
    gitHookSecret: <REDACTED>
