apiVersion: apps/v1
kind: Deployment
metadata:
  name: triggermesh-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: triggermesh-operator
  template:
    metadata:
      labels:
        name: triggermesh-operator
    spec:
      serviceAccountName: triggermesh-operator
      containers:
        - name: triggermesh-operator
          image: gcr.io/triggermesh/operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "triggermesh-operator"
