kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggermesh-user
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups:
      - ''
      - apps
      - batch
      - build.knative.dev
      - eventing.knative.dev
      - extensions
      - messaging.knative.dev
      - messaging.triggermesh.dev
      - rbac.authorization.k8s.io
      - serving.knative.dev
      - sources.eventing.knative.dev
      - sources.eventing.triggermesh.dev
      - tekton.dev
    resources:
      - apiserversources
      - awscodecommitsource
      - awscognitosource
      - awsdynamodbsource
      - awsiotsource
      - awskinesissource
      - awssqssource
      - awssqssources
      - azureeventhubsource
      - azurestorageblobsource
      - azurestoragequeuesource
      - brokers
      - builds
      - camelsources
      - channels
      - configurations
      - containersources
      - cronjobsources
      - deployments
      - gcppubsubsources
      - githubsources
      - gitlabsources
      - inmemorychannels
      - kafkasources
      - kinesischannels
      - kuberneteseventsources
      - pipelineresources
      - pipelineruns
      - pipelines
      - pods/exec
      - pubsubsources
      - revisions
      - routes
      - secrets
      - serviceaccounts
      - services
      - sinkbindings
      - subscriptions
      - taskruns
      - tasks
      - triggers
