{{- $ingress := .Values.backend.ingress -}}
{{- $fullName := print (include "triggermesh.fullname" .) "-backend" -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.backend.baseHost }}
      {{- if $ingress.secretName }}
      secretName: {{ $ingress.secretName }}
      {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.backend.baseHost }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
